/// Environment configuration — loaded from --dart-define at build time.
/// Firebase config is in firebase_options.dart (generated by FlutterFire CLI).
/// Never commit real keys. See .env.example in root.
class Env {
  static const backendUrl = String.fromEnvironment(
    'BACKEND_URL',
    defaultValue: 'https://your-worker.railway.app',
  );
}
